### ISSUE TITLE
A3 Milestones

### ISSUE THREAD

**Issue by antonioalmeida** [antonioalmeida/presto#1]
#### High priority - stuff reused in most pages
- [x] Finish navbar (add links to user dropdown, add search bar, add notifications preview example)
- [x] Finish questions/answers cards
- [x] Fix footer positioning and design - [read here](https://css-tricks.com/couple-takes-sticky-footer/#article-header-id-3)
- [x] Finish 'add question' popup

#### Medium priority 
- [x] Dedicated sign up page
- [x] Dedicated login page
- [x] Dedicated about page
- [x] Admin page - manage users and moderators
- [x] Finish user page
- [ ]  Finish search page(s) 

#### Low priority
- [x] Logged in version of feed
- [ ] Define primary and secondary color

Can't think of anything else right now. Feel free to add more stuff, and to create separate issues for any of these topics so we can discuss them
